# Github Pages
# Various options to ensure the Github repository is able to be displayed properly in GH Pages

# Tutorial here: 
# https://biodata-club.github.io/githubPagesTutorial

# Error Fixes
# Github Metadata plugin requires API key https://github.com/github/pages-gem/issues/399#issuecomment-361091215
repository: richpeck/engine_demo # Required to build with Github Actions

# System
# Overall options for the entire site
locale:   en_GB
timezone: Europe/London
#baseurl: /engine_demo # required to get relative_url working with our custom build script

# General
# Give us the ability to manage the overall structuer of the site etc
title: JS Engine Demo
description: Demonstration engine for basic 3D engine

# Translations
# Allows us to use translatable text throughout the app
languages: ["en"]
exclude_from_localizations: ["assets"]
defaultLang: en
languageNames:
  en: English

# Plugins
# https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/about-github-pages-and-jekyll#plugins 
plugins:
  - "jekyll-github-metadata" # required to change the header area
  - "jekyll-seo-tag" # allows us to edit the various meta tags for each page
  - "jekyll-sitemap" # Used to provide robots.txt etc
  - "jekyll-multiple-languages-plugin" # provides translatability for our app

# Exclude
# Exclude these files from the build.
exclude:
  - .github
  - .editorconfig
  - .gitignore
  - _config.yml
  - vendor # required to avoid issue with build using custom GH Action (https://github.com/jekyll/jekyll/issues/5267#issuecomment-241379902)
  
# Github
github:
  is_project_page: false