# Sample workflow for building and deploying a Jekyll site to GitHub Pages
name: Deploy Jekyll with GitHub Pages dependencies preinstalled

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write # required to get the deploy script to work (https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-first-deployment-with-github_token)
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Build job
  build:
    name:    Build
    runs-on: ubuntu-latest
    steps:
    
      # Get Git repo
      - name: 📂 Checkout
        uses: actions/checkout@v3
        
      # Use ruby/setup-ruby to shorten build times
      # https://github.com/ruby/setup-ruby
      - name: 💎 Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1 # Not needed with a .ruby-version file
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically

      # use jekyll-action-ts to build
      # https://github.com/limjh16/jekyll-action-ts
      - name: 🔨 Install Dependencies & Build Site
        uses: limjh16/jekyll-action-ts@v2
        with:
          enable_cache: false

      - name: 🚀 Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          keep_files: true
          allow_empty_commit: true

  # Deployment job
  #deploy:
  #  name: Deploy
  #  runs-on: ubuntu-latest
  #  needs: build
   # steps:
    #  - name: 🚀 Deploy
     # - uses: peaceiris/actions-gh-pages@v3
      #  with:
       #   github_token: ${{ secrets.GITHUB_TOKEN }}
